# Generated by Django 2.2.5 on 2020-09-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200911_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('sub_type', models.BooleanField()),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('same_address', models.BooleanField()),
                ('save_info', models.BooleanField()),
                ('credit', models.BooleanField()),
                ('debit', models.BooleanField()),
                ('paypal', models.BooleanField()),
                ('cc_name', models.CharField(max_length=100)),
                ('cc_number', models.IntegerField()),
                ('cc_expiration', models.CharField(max_length=10)),
                ('cc_cvv', models.IntegerField()),
            ],
        ),
    ]
