# Generated by Django 2.2.5 on 2020-09-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200913_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='annual_subs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='monthly_subs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekly_subs',
        ),
    ]
