# Generated by Django 2.2.5 on 2020-09-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200913_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='cc_cvv',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='cc_expiration',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='cc_name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='cc_number',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='debit',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='paypal',
        ),
    ]
