# Generated by Django 2.2.5 on 2020-09-15 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200915_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_of_signup',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
