# Generated by Django 3.1 on 2020-09-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubEx', '0005_auto_20200903_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
