# Generated by Django 3.1 on 2020-09-17 08:47

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ClubEx', '0007_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
