# Generated by Django 2.2.5 on 2020-09-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubEx', '0006_auto_20200910_2159'),
        ('ClubEx', '0008_auto_20200917_2047'),
    ]

    operations = [
    ]
