# Generated by Django 2.2.5 on 2020-09-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubEx', '0009_merge_20200918_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-video_name',)},
        ),
        migrations.AddField(
            model_name='video',
            name='video_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
